defaults: &defaults
  working_directory: ~/app
  docker:
    - image: fiverr/circleci_node_12
      auth:
        username: $DOCKER_USER
        password: $DOCKER_PASS

version: 2
jobs:
  danger:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm i --production
      - run:
          name: danger
          command: ./bin.js
  publish:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm i
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Code linting
          command: npm run lint -- --plugin log
      - run:
          name: Publish to NPM
          command: npx published --git-tag

workflows:
  version: 2
  ci-cd:
    jobs:
      - danger:
          context: org-global
      - publish:
          context: org-global
